### ISSUE TITLE
nový onboarding pro družstvo

### ISSUE THREAD

**Issue by vpithart** [HKFree/UserDB#110]
Funkci "přidat uživatele" rozdělit na dvě (logicky, v kódu zůstane v jednom tvoření nového uživatele):
1. registrace člena spolku
2. přidat uživatele - družstvo

K dořešení v zadání:
- [x] jak se má nastavit money_aktivni? Dnes je 1 při TypClenstvi_id > 0
- [x] TypClenstvi_id dnes nelze dát na NULL
- [x] Obsah emailů pro družstvo (viz MailService::sendConfirmationRequest)
- [x] Zrušeno: Obsah pdf form po kliknutí na potvrzovací email při založení zákazníka v družstvu

Funkce "přidat uživatele - družstvo" bude skoro stejná. Rozdíly:
- [x] povinně zadávat datum narození
- [x] doladit templates/Uzivatel/pdf-form.latte - registracni formular po registraci do spolku
- [x] nezadávat "typ členství" (v databázi nastavit NULL)
- [x] potvrzovací e-mail "klikni na odkaz" zachovat
- [x] negenerovat registrační formulář a neposílat ho mailem
- [x] generovat účastnickou smlouvu - App\Services\RequestDruzstvoContract
- [x] odesílání emailů a potvrzení confirmu přehodit do různých metod podle právního vztahu, ať v tom není bordel (teoreticky tak do budoucna budeme umět oba právní vztahy najednou - bude muset kliknout dvakrát a udělá to různé akce podle toho co potvrdil)
- [x] zrušit hlášku "internetu bude aktivní za 15 minut"
hotovo, pokud se jednalo jen o toto: `$this->flashMessage('E-mail s žádostí o potvrzení registrace byl odeslán. PŘIPOJENÍ K HLAVNÍMU POČÍTAČI BUDE FUNGOVAT DO 15 MINUT.');`

Přidávám podmínku, že:
- [x] nepůjde založit uživatele s právním vztahem ke spolku a k družstvu najednou - zjednoduší se tím logika pro odesílání emailů.

TODO:
- [x] UzivatelActionsPresenter::actionSendRegActivation

**Comment by lubikx** [comment]
@vpithart myslim ze by zde bylo jednodussi nechat to ve stejnem formulari a jen podle toho, jak to uzivatel nastavi nasledne provest co je potreba

tedy pokud nastavim, ze ma pravni vztah k druzstvu, tak vynutim zadat datum narozeni a po ulozeni se mu vygeneruje ucastnicka smlouva

pokud zaroven nastavim ze ma pravni vztah ke spolku, tak se provedou veci souvisejici se spolkem

souhlas?

**Comment by vpithart** [comment]
> souhlas?

Určitě. Mám na mysli dvě různý workflow, to nemusí nutně bejt 2 různý formuláře, čili ano, nechat jeden.

**Comment by lubikx** [comment]
@vpithart Uzivatel.TypClenstvi_id dnes nemuze byt null, ale je to signed int, tak jsou dve varianty, bud umoznime nastavit NULL migraci nebo vytvorime v tabulce TypClenstvi zaznam s -1 a textem treba Nenastaveno - to ma asi vetsi sanci, ze to nikde nic nerozbije

**Comment by lubikx** [comment]
Dnes se podle typu clenstvi nastavuje atribut money_aktivni, jaka ma byt logika s druzstvem?
```php
            if ($values->TypClenstvi_id > 0) {
                $values->money_aktivni = 1;
            } else {
                $values->money_aktivni = 0;
            }
```

**Comment by lubikx** [comment]
Přidávám podmínku, že nepůjde založit uživatele s právním vztahem ke spolku a k družstvu najednou - zjednoduší se tím logika pro odesílání emailů.

**Comment by lubikx** [comment]
Návrh textu emailu:

```php
$fromAddress = 'družstvo hkfree.org oblast ' . $uzivatel->Ap->Oblast->jmeno . ' <oblast' . $uzivatel->Ap->Oblast->id . '@hkfree.org>';


            ->setSubject('Žádost o potvrzení registrace zákazníka družstva hkfree.org - UID ' . $uzivatel->id)
            ->setHtmlBody('Dobrý den,<br><br>pro dokončení registrace zákazníka družstva hkfree.org je nutné kliknout na ' .
                'následující odkaz:<br><br><a href="' . $link . '">' . $link . '</a><br><br>' .
                'Veškeré relevantní dokumenty naleznete na stránkách <a href="https://druzstvo.hkfree.org">druzstvo.hkfree.org</a> v sekci Základní dokumenty.<br><br>' .
                'S pozdravem hkfree.org, internetové družstvo');
```

**Comment by lubikx** [comment]
@vpithart prosím ještě o odpověď k tomu typu členství a úplně nechápu to generování smlouvy (my zakládáme uživatele ještě předtím než máme smlouvu nebo založíme, ověříme email a teprve pak mu posíláme digisign na email?)

aktuální rozpracování se můžeš mrknout zde: https://github.com/HKFree/UserDB/pull/117

**Comment by vpithart** [comment]
Radeji bych docilil toho ze bude TypClenstvi_id NULL. Snad tech veci ktery se tim "rozbijou" neni mnoho.
Postup založení by měl bejt: založíš uživatle v userdb, odešle se ověřovací link na e-mail, po ověření se vygeneruje a odešle smlouva k podpisu.
(odeslání smlouvy je placená služba, tj. je dobrý předtím mít ověřeno že ten e-mail je funkční a že tam je někdo schopen číst)
