### ISSUE TITLE
Vsechny assets mit ulozene a linkovane lokalne

### ISSUE THREAD

**Issue by pavkriz** [HKFree/UserDB#2]
Vsechny assets (JS, CSS,....; konkretne napr. jQuery) linkovat z lokalniho adresare (ne z CDN), aby aplikace fungovala i bez pristupu k internetu. V pripade potreby je mozno client-side dependencies managovat [bowerem](http://bower.io/).

**Comment by evildivine** [comment]
jquery js a css bylo ulozeno lokalne .. nic dalsiho tam asi uz neni
