### ISSUE TITLE
Zrušit index potížisty

### ISSUE THREAD

**Issue by vpithart** [HKFree/UserDB#23]
Situace, kdy sám člen uvidí (na mém displeji) ty škaredý lebky je pro mě nepříjemná a komplikuje mě to práci.

**Comment by bkralik** [comment]
Nazdar,
můžeme ho určitě udělat schovávací, to není problém. Ale i v souvislosti s blížícím se GDPR bych upozornil, že nechávat člena nakukovat do userdb je velmi nezodpovědné...

**Comment by vpithart** [comment]
OK; pokud jde o nakukovani, samozrejme je to jeho vlastni zaznam.

**Comment by evildivine** [comment]
prejmenovano na "Index spokojenosti člena"
to uz nikoho poburovat nebude
