### ISSUE TITLE
userdb - synchronizace prav so do hlasovani

### ISSUE THREAD

**Issue by coudek** [HKFree/UserDB#3]
Ahoj, 

hlasovani si synchronizuje data o SO z tabulky(view) userdb.roles
pomoci selectu: SELECT uid,'spravce',curdate(),'2100-01-01' from userdb.roles where name='SO' and enabled=1 order by uid;

Userid 7820 neni v tom selectu, proto si hlasovani mysli ze neni SO. 

diky
coudek

**Comment by evildivine** [comment]
Nic takového jako tabulka roles není ... to taháš ze staré userdb a to je k ničemu

 

SELECT S.Uzivatel_id as uid, T.id as rid, T.text as name FROM SpravceOblasti S LEFT JOIN TypSpravceOblasti T ON S.TypSpravceOblasti_id=T.id ORDER by rid,uid

 

Connection detaily poslu primo tobe mailem

 

Radim

**Comment by bkralik** [comment]
Co takhle změnit heslo do té staré DB, ať se vidí, co se všechno rozbije a může se to opravit?

**Comment by evildivine** [comment]
Souhlas

Dne středa 17. února 2016 bkralik <notifications@github.com> napsal(a):
