### ISSUE TITLE
ping/tracert test

### ISSUE THREAD

**Issue by locutus01** [HKFree/UserDB#31]
K dané IP v userdb přidat "pingátko" případně traceroute, které ověří dostupnost IP v síti. Když např. potřebuju ověřit, zda jede jeden vchod na LAN bylo by to pro rychlou kontrolu 100x jednodušší než kopírovat IP někam do konzole a pingat tam. Výsledek pingu může být např. v novém okně prohlížeče

**Comment by bkralik** [comment]
Je v plánu, aktuálně už funguje pingátko, které pingá celé hkfree každých pět minut a ukládá to do databáze, je potřeba to jen zaintegrovat do userdb...

**Comment by evildivine** [comment]
zaintegrováno
