### ISSUE TITLE
V logu zmen jsou videt citlive udaje

### ISSUE THREAD

**Issue by pavkriz** [HKFree/UserDB#4]
V logu zmen (Napr. na AP) jsou videt citlive udaje (hesla) i kdyz je v hlavnim zobrazeni nevidim (tedy asi nemam videt). Zvazit skryti nekterych udaju v logu zmen nebo log "cizim" ani nezobrazovat?

**Comment by evildivine** [comment]
hesla se v logu nadále neukazují
