### ISSUE TITLE
Pomaly SELECT z DB

### ISSUE THREAD

**Issue by coudek** [HKFree/UserDB#47]
Select ktery se pouziva pro synchronizaci dat s igw je pomaly(30sec).
SELECT IPAdresa.ip_adresa FROM IPAdresa, Uzivatel WHERE ( IPAdresa.internet =1 AND IPAdresa.Uzivatel_id = Uzivatel.id AND Uzivatel.money_aktivni =1 ) OR ( IPAdresa.internet =1 AND IPAdresa.Uzivatel_id IS NULL ) GROUP BY IPAdresa.ip_adresa

Chybi index na sloupci Uzivatel.money_aktivni

prosim fix.

**Comment by Kendak** [comment]
Index pridan na Uzivatel.money_aktivni
ALTER TABLE `Uzivatel` ADD INDEX(`money_aktivni`); 
dale na IPAdresa.Internet, tam take nebyl
ALTER TABLE `IPAdresa` ADD INDEX(`internet`);

Vysledek stale spatny. 

Prvni select trva 1sec:
SELECT IPAdresa.ip_adresa FROM IPAdresa, Uzivatel WHERE IPAdresa.internet =1 AND IPAdresa.Uzivatel_id = Uzivatel.id AND Uzivatel.money_aktivni =1
Druhy trva 6sec:
SELECT IPAdresa.ip_adresa FROM IPAdresa, Uzivatel WHERE IPAdresa.internet =1 AND IPAdresa.Uzivatel_id IS NULL GROUP BY IPAdresa.ip_adresa
Treti za unionem 1sec

celkove to vsak s tim OR a UNION trva 40sec, nejvice tomu pridava OR, tj spojeni prvnich dvou dotazu zpusobi 30sec vysledek.


Vyreseno na aplikacni urovni, udelal jsem si tri selecty, jejichz vysledky jsem v aplikaci spojil v jeden. Vysledek behu je nyni 7.5sec. Oproti puvodnim 40sec se jedna o zasadni pozitivni vysledek.

**Comment by pavkriz** [comment]
Bylo by byvalo potreba podivat se, jaky index to pouzivalo puvodne a udelat druhy, ktery bude rozsiren o ty dalsi potrebne sloupce. Mit nekolik indexu, kde kazdy je jen pro jeden sloupec opravdu nemusi nijak pomoct.

**Comment by bkralik** [comment]
A přidal si ten index jenom na ostré databázi nebo si ho upravil i tady v datech na githubu, @Kendak ?
