### ISSUE TITLE
přímý link na WinBox Android

### ISSUE THREAD

**Issue by cermis** [HKFree/UserDB#49]
V UDB je link na winbox z woken, pokud máme dle návodu registrované URI schéma. 
Mým požadavkem, prosím, by bylo, aby toto schéma bylo dynamické podle platformy, na které je zobrazena stránka. 
Pro Android a aplikaci Mikrotik funguje URI schéma ve tvaru "winbox://hostname/user/password", bylo by dobré, kdyby se dalo na ty mikrotiky dostávat bez přepínání oken v mobilu a přepisování hesel. Na mobilu je taková funkce víc než nutnost. Prosím, o implementaci.

**Comment by vpithart** [comment]
Je to tam. Autodetekce user-agent:
android: `winbox://hostname/user/password`
windows: `winbox:hostname;user;password`

Pro android pak vypada odkaz takto:
<img width="254" alt="Screen Shot 2020-04-23 at 10 04 47" src="https://user-images.githubusercontent.com/20604326/80074754-f358a080-8549-11ea-9b31-e212ad1571cb.png">
