### ISSUE TITLE
družstvo: DB model pro lidi - spolek/družstvo

### ISSUE THREAD

**Issue by vpithart** [HKFree/UserDB#63]
Pro plynulý přechod připojenců na družstvo je třeba upravit datový model tak, aby bylo možné jednoznačně evidovat stavy:

- je členem spolku ano/ne
  - typ členství (řádné, čestné, zrušené, atp. - tady žádná změna)
  - je správce oblasti - žádná změna
- je ve vztahu s družstvem ano/ne
  - vztah "připojenec" bude mít záznam tabulce `SmlouvaUcastnicka`, viz [64](https://github.com/HKFree/UserDB/issues/64).
  - vztah "družstevník = správce" bude mít záznam tabulce `SmlouvaSpravce`, viz [65](https://github.com/HKFree/UserDB/issues/65).
  - vztah "člen představenstva"  bude mít záznam tabulce `SmlouvaPredstavenstvo`, TBD 

**Acceptance Criteria**
- v tabulce `Uzivatel` jsou 2 nový sloupce: `spolek` a `druzstvo`, `smazano` všechny tři boolean
- u všech je nastaveno `spolek` = `true` a `druzstvo` = `false`, `smazano` = `false`
- defaultní hodnota (při INSERT INTO) je `spolek` = `true` a `druzstvo` = `false`, `smazano` = `false`
- ~defaultní hodnota typu členství `TypClenstvi_id` je NULL~

**Comment by bkralik** [comment]
Tohle bude o dost složitější
 - TypClenstvi dneska indikuje, jestli to je existující člen a nebo ne. Uživatele nemažeme, pouze je nastavujeme jako zrušení. Co budeme dělat s lidmi ve družstvu? Brát neexistenci platné smlouvy jako indikátor jestli je uživatel smazaný a nebo ne mi nepřijde úplně vhodné.
 - Pokud bychom TypClenstvi_id nastavili jako NULL (dneska je not null), tak to bude znamenat úpravu na dost místech v UserDB
 - Co takhle založit nový TypClenstvi v tabulce TypClenstvi jako "pouze druzstvo" nebo "druzstvo" nebo tak? S tím že stále bude platit - je TypClenstvi zrušený => uživatele nezobrazujeme. A když bude člověk ve spolku i družstvu, tak holt bude mít typčlenství podle spolku.

**Comment by opth** [comment]
> Co takhle založit nový TypClenstvi v tabulce

Asi to bude cesta nejmensiho odporu. I v druzstvu prece budeme mit v budoucnu "zrusene" ucastniky z ruznych duvodu.

> A když bude člověk ve spolku i družstvu, tak holt bude mít typčlenství podle spolku.

Mozna jeste chceme mit nejake rozliseni ucastnik a druztevnik (jako je ted SO), ne?

**Comment by bkralik** [comment]
No, ono to je těžké - teoreticky se zrušení účastníci dají poznat podle neexistující smlouvy. Ale nevím jestli to nebude implementačně dost peklo a taky jestli to je správný krok (po zrušení smlouvy by se účastník asi neměl zrušit hned a tak)

Rozlišení účastník a družstevník by se mělo dělat podle existující smlouvy

**Comment by vpithart** [comment]
Rozliseni ucastnik a druzstevnik necht je podle boolean sloupcu: `spolek` a `druzstvo`. Pro cca 100 lidi je pravdepodoby, ze budou oboje. Muze bejt druzstevnik v prechodovych stavech, napr. novej uz existuje v DB ale jeste nema smlouvu ani vygenerovanou.

Zruseny ucastniky jsem mel opravdu na mysli identifikovat tim, ze maji zrusenou smlouvu. (btw. k tomu by asi nakonec bylo prehlednejsi mit ucastnicky smlouvy prece jen ve zvlast tabulce). Mate ale pravdu ze nejakej "soft delete" flag, typu jako je TypClenstvi=zruseno, to by chtelo.

Sloupec TypClenstvi bycjh ponechal jenom pro spolek. Proste pojem "členství" v druzstvu neexistuje a nechci to ohejbat.

**Comment by bkralik** [comment]
Nevím jak s tím dál...
boolean spolek lehce koliduje s TypClenstvi. Když se zruší členství, tak se nastaví i spolek na false? A když se zruší smluvní vztah ve družstvu, tak se nastaví i družstvo na false? Jak se pak pozná co ten člověk byl?
Jenže když zase nebudeme nastavovat spolek na false, tak všude bude zobrazený label spolek a tak bude vlastně k ničemu...

**Comment by bkralik** [comment]
Hotovo, vyřešeno v commitu https://github.com/HKFree/UserDB/commit/42c60a5887fd004a9b92af5ffbd7a0e00527fcae
