### ISSUE TITLE
družstvo: DB model pro smlouvy - družstevník (správce)

### ISSUE THREAD

**Issue by vpithart** [HKFree/UserDB#65]
Evidence smluv pro členy družstva - fyzické osoby (správce) podle stanov:
```
III. ČLENSTVÍ V DRUŽSTVU
III.1 Členem družstva může být zletilá fyzická osoba ... která splní všechny podmínky stanovené zákonem a ...
III.2.1 Uzavřením a plněním smlouvy o správcovství oblasti, která vymezuje povinnosti a práva člena týkající se správy telekomunikační infrastruktury
```

**Životní cyklus smlouvy:** 
1. smlouva vygenerovaná a připravená k podpisu
2. smlouva podepsaná (=platná =účinná)
3. smlouva ukončená

Template smlovy je soubor typ PDF nebo ODT.
Smlouvy mají parametry, např. jméno/příjmení/datum narození

Jeden `Uzivatel` může mít víc smluv.

**Stavy:**
Smlouva vygenerovaná a připravená k podpisu: existuje v DB, timestamp2 je null, timetamp3 je null, aktuální podepsaná smlouva je null.

Smlouva podepsaná (=platná =účinná): existuje v DB, má timestamp2, má timestamp3, aktuální podepsaná smlouva tam je, timetamp4 je null

Smlouva ukončená: má vše jako předchozí a taky má timestamp4.

**Acceptance Criteria**
- existuje nová tabulka `SmlouvaSpravce`, jeden záznam = jedna smlouva
- sloupce (hezky pojmenovat):
  - `id` číslo autoincrement 
  - `Uzivatel_id` odkazuje do tabulky `Uzivatel`
  - timestamp1 kdy byla smlouva vygenerovaná, default "teď"
  - timestamp2 kdy byla smlouva podepsaná správcem
  - timestamp3 kdy byla smlouva podepsaná družstvem (asi bude implicitní, tj. naskenovaný podpis)
  - ID smlouvy (UUID identifikátor od signature providera - digisign)
  - šablona ze který je smlouva vygenerovaná
    - název souboru např "smlouva_o_spravcovstvi_template_v1.pdf"
    - content-type např "application/pdf"
    - obsah souboru (? buď přímo BLOB v databázi nebo odkaz na filesystem)
  - parametry smlouvy
  - aktuální podepsaná smlouva
    - název souboru např "smlouva_o_spravcovstvi_uid3579_9876.pdf"
    - content-type např "application/pdf"
    - obsah souboru (? buď přímo BLOB v databázi nebo odkaz na filesystem)
  - timestamp4 kdy byla smlouva ukončená

**Comment by lanik** [comment]
řešeno v issue #64
