### ISSUE TITLE
družstvo: UI pro generování účastnický smlouvy

### ISSUE THREAD

**Issue by vpithart** [HKFree/UserDB#72]
## Tlačítkové generování účastnický smlouvy
- tlacitko pro generovani co bude opravdu generovat smlouvu: tzn call na script `odeslat-k-podpisu`
  - speed bump
    - _Účastnická smlouva pro Jméno Příjmení bude odeslána k podpisu na adresu example@example.org. Pokračovat? ANO NE_
  - pri kliknuti na button vyrobit minilaisticky zaznam v databazi a pak to dat jako argument sciptu
  - do DB `Smlouva` insertnout `typ=uzivatelska` a jinak nic; vygeneruje se auto increment ID
  - spustit skript `./bin/digisign-generovat-ucastnickou-smlouvu.php <ID>` 
  - diky tomu bude v databazi uz zaznam o tom, ze se na tlacitko kliknulo, a kdy

https://www.geeksforgeeks.org/how-to-execute-a-background-process-in-php/

- script bude trvat desitky sekund tzn chceme indikovat ze "se to děje"
  - zabránit opakovanemu stisknuti
  - perhaps: nejak hezky reprezentovat ze se to deje, a pak ze je hotovo

**Comment by opth** [comment]
Button by měl být dole pod seznamem sluv na user prehled. 
Zelenej `+ Vygenerovat a odeslat novou smlouvu`.
Pridat zaznam do LOGu
