### ISSUE TITLE
Filtrovani CC dle mych oblasti

### ISSUE THREAD

**Issue by PeS-hkfree** [HKFree/UserDB#8]
Ahoj,
bylo by vhodne umoznit filtrovat prehled CC podle vlastnich oblasti. Pripadne tam dat rovnou filtrovatani a na tlacitko zobrazeni vsech jak to je ted.

Diky, PeS

**Comment by evildivine** [comment]
pridan sloupec AP s moznosti razeni a filtrace ... lze tak filtrovat a radit dle nazvu AP
